### ISSUE TITLE
TypeError on storing alerts locally

### ISSUE THREAD

**Issue by duhow** [midokura/grafana-sync#12]
```python
Traceback (most recent call last):
  File "/home/duhow/midokura/grafana-sync/./grafana-sync.py", line 474, in <module>
    sys.exit(main())
  File "/home/duhow/midokura/grafana-sync/./grafana-sync.py", line 449, in main
    save_folder(f, args.target, exist_skip=not args.force_overwrite)
  File "/home/duhow/midokura/grafana-sync/./grafana-sync.py", line 162, in save_folder
    filename_pattern = f'{f["title"]}_{f["uid"]}'
TypeError: string indices must be integers
```

**Comment by LIII-XXII** [comment]
fixed by !14
